<?php

function pet_menu ()
{
    $items = array();
    $items['favorite_pet'] = array(
            'title' => 'My favorite Pet',
            'page callback' => 'favorite_pet',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function favorite_pet ()
{
    return '<h3>Corgi puppies are great.</h3>
            <img src="http://www.thatcutesite.com/uploads/2010/11/cute_corgi_puppy.jpg">
            <p>Visit her website <a href="http://corgiaddict.com">here</a></p>';
}
